url: https://basketball-gm.com

excerpt_separator: <!--more-->
permalink: /blog/:year/:month/:title/

pagination:
  enabled: true
  permalink: /page/:num/
  sort_reverse: true
  trail:
    before: 2
    after: 2

tag_page_layout: tag-index
tag_page_dir: /blog/tag/
tag_permalink_style: pretty

author: Basketball GM Commissioner
feed:
  path: feed/index.xml

future: true

# This stuff is just used by jekyll-seo-tag
title: Basketball GM
description: >-
  Basketball GM is a single-player basketball management simulation game. Set
  your roster, make trades, draft prospects, manage your finances, and try to
  build a dynasty. Play it in your browser now, completely 100% free!
facebook:
  publisher: https://www.facebook.com/basketball.general.manager
twitter:
  username: basketball_gm
logo: /files/logo.png
social:
  links:
    - https://twitter.com/basketball_gm
    - https://www.facebook.com/basketball.general.manager

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- README.md
